added reverse option for critical and warning thresholds
sensu-plugins/sensu-plugins-snmp pull request #18
Opened 2017-09-07 11:32 UTC by kierenhamps

## Pull Request Checklist

**Is this in reference to an existing issue?**
NO

#### General

- [ Yes ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ N/A ] Update README with any necessary configuration snippets

- [ N/A ] Binstubs are created if needed

- [ Yes for check-snmp.rb ] RuboCop passes

- [ Yes for check-snmp.rb ] Existing tests pass

#### New Plugins

- [ N/A ] Tests

- [ N/A ] Add the plugin to the README

- [ N/A ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
To provide the capability to reverse the logic used when evaluating critical and warning states.
Use case: SNMP provides a value as an output but you want to be alerted if that value is below a threshold, rather than above it.
Example: Power Socket Voltage: 240v, Warn when below 230V, Critical when below 210v.

#### Known Compatability Issues
None known

2017-09-08 01:59 UTC, majormoses requested changes
Thanks for the contribution!
What is the use case? I am having a hard time understanding why you `-o ge --reverse` is different than `--o le` and what benefit the new way of using it has over the previous mechanism.

2017-09-08 01:59 UTC, majormoses commented on CHANGELOG.md
> +- check-snmp.rb: Option to reverse login in critical/warning thresholds
logic not login.

2017-09-08 01:59 UTC, majormoses commented on bin/check-snmp.rb
> +         description: 'Revese the logic of the test for warning and critical thresholds',
This is not an accurate description if I am not misunderstanding the code. I understand it as "Reverse the operator passed in". Am I missing something?

2017-09-08 08:36 UTC, kierenhamps commented
Amazing, I didn't see the "-o" option for changing the operator.... In which case. You are correct, my change is completely unnecessary as "-o le" does the same job.

Sorry for the oversight. I'll close this request.
Thanks for your kind comments.

2017-09-08 08:36 UTC, closed without merging

2017-09-09 00:18 UTC, majormoses commented
No problem! I do appreciate the willingness to help.