Sensu Go Enablement
sensu-plugins/sensu-plugins-snmp pull request #34
Opened 2019-11-09 18:37 UTC by asachs01

## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [x] Update Changelog following the conventions laid [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [x] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [x] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
Adds asset capability to plugin collection.

#### Known Compatibility Issues
Drops support for < Ruby 2.3 & requires sensu-plugin 4.0

2019-11-18 16:57 UTC, asachs01 commented
ping @cwjohnston & @majormoses

2019-11-18 19:49 UTC, cwjohnston requested changes
I've added a few suggestions to change manifest -> definition. Anchor links may need some help as well, to ensure TOC links go to the right place in the doc.

As this plugin collection depends on the ruby-runtime asset, we also need to call out that dependency.

2019-11-18 19:49 UTC, cwjohnston commented on README.md
> +    - [Asset manifest](#asset-manifest)
```suggestion
    - [Asset definition](#asset-definition)
```

2019-11-18 19:49 UTC, cwjohnston commented on README.md
> +    - [Check manifest](#check-manifest)
```suggestion
    - [Check definition](#check-definition)
```

2019-11-18 19:49 UTC, cwjohnston commented on README.md
> +##### Asset manifest
```suggestion
##### Asset definition
```

2019-11-18 19:49 UTC, cwjohnston commented on README.md
> +##### Check manifest
```suggestion
##### Check definition
```

2019-12-07 09:28 UTC, majormoses approved these changes
LGTM

2020-03-20 19:05 UTC, jspaleta commented
Merging, I'll clean up anything small that has drifted

2020-03-20 19:05 UTC, merged